baseURL = "https://foodrescueph.site/"
languageCode = "en-us"
title = "Food Rescue Philippines"

disableHugoGeneratorInject = true
disableKinds = ["categories"]

formcarry = "https://formcarry.com/s/fG_9Cbp0qe"

googleAnalitycsID= "G-2YEM6FJ3MT"



enableRobotsTXT = true
ignoreErrors = ["error-remote-getjson"]

paginate = 8
paginatePath = "p"

[outputs]
home = ["HTML","RSS"]

[params]

  # [params.segment]
  #   id = "kUqH89S3AJWXRDFvqlkrcHDdWRLaZru2"
    
  [params.announcement]
    show = true

  [params.logo]
    mobile = "/icons/main.png"
    desktop = "/icons/main.png"
    desktop_height = "36px"
    desktop_width = "131px"
    alt = "Food Rescue Philippines"

  [params.homepage_meta_tags]
    meta_description = "We rescue food waste and reprocess them for feeding programs or for donations to the poor to prevent hunger and malnutrition."
    meta_og_title = "Food Rescue Philippines"
    meta_og_type = "website"
    meta_og_url = "https://foodrescueph.site"
    meta_og_description = "We rescue food waste and reprocess them for reuse or for donations to the poor to prevent hunger and malnutrition."
    meta_twitter_card = "summary_large_image"
    # meta_twitter_site = "@executebig"
    # meta_twitter_creator = "@executebig"

[menu]
  # Main Menu

  [[menu.main]]
      name = "Team"
      url = "/team/"
      weight = 1

  [[menu.main]]
      name = "Rescues"
      url = "/rescues/"
      weight = 3

  # [[menu.main]]
  #     name = "Subscribe"
  #     url = "/subscribe"
  #     weight = 7

  # Footer Menu
      
  [[menu.about]]
      name = "Team"
      url = "/team/"
      weight = 1
  
  [[menu.about]]
      name = "Contact"
      url = "/contact/"
      weight = 2

  [[menu.about]]
      name = "Donate"
      url = "/donate/"
      weight = 3


  [[menu.services]]
    name = "Rescues"
    url = "/rescues/"
    weight = 4

  # Resources Menu
  
  [[menu.resources]]
    name = "Privacy"
    url = "/privacy/"
      weight = 5

  [[menu.resources]]
    name = "Conduct"
    url = "/conduct/"
      weight = 4
      

[taxonomies]
  rescues_tags = "rescues/tags"

[sitemap]
  filename = "sitemap.xml"
  priority = 0.5
  